CREATE DATABASE ERP
GO

USE ERP
GO

CREATE TABLE [dbo].[Product](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Price] DECIMAL(15,4) NOT NULL,
	[Image] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT PK_Products_Id PRIMARY KEY CLUSTERED (Id)
)
GO